#
# This file is part of the fastimage node module. Copyright (C) 2015 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

language: node_js
script: npm run-script travis-ci
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
notifications:
  email: false
