#
# This file is part of the fastimage npm package. Copyright (C) 2015 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

language: node_js
script: npm run-script travis-ci
node_js:
  - "5.0"
  - "5.5"
  - "5"
notifications:
  email: false
